import turtle
stift=turtle.Pen()
turtle.bgcolor('navy')

for x in range(999):
	stift.forward(x)
	stift.left(200)
	stift.pencolor('green')
	stift.forward(100)
	stift.left(200)
	stift.pencolor('white')
	stift.forward(100)
	stift.left(200)
	stift.pencolor('purple')
	stift.forward(100)
	stift.left(200)
	stift.pencolor('cyan')
	stift.forward(x)
	stift.left(30)
	stift.pencolor('red')
	stift.forward(x)
	stift.left(2)
	stift.circle(100)
	stift.up()
	stift.forward(123)
	stift.down()
	stift.pencolor('brown')
turtle.Screen().exitonclick()
