import turtle
stift=turtle.Pen()
turtle.bgcolor('gold')

for x in range(1234567890):
	stift.forward(x)
	stift.left(200)
	stift.pencolor('green')
	stift.forward(100)
	stift.left(200)
	stift.pencolor('blue')
	stift.forward(100)
	stift.left(200)
	stift.pencolor('purple')
	stift.forward(100)
	stift.left(200)
	stift.pencolor('cyan')
	stift.forward(x)
	stift.left(30)
turtle.Screen().exitonclick()
